# Generated by Django 3.2.4 on 2021-06-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_listcontact_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listcontact',
            old_name='satuts',
            new_name='status',
        ),
    ]
